name: CI
on: push
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
     steps:
      - name: Set URL
        id: set-url
        run: echo "::set-output name=url::https://example.com/path/to/resource/value"

      - name: Extract Last Value
        id: extract-last-value
        run: |
        URL="${{ steps.set-url.outputs.url }}"
        last_value=$(basename "$URL")
        echo "Last Value: $last_value"




