name: CI
on: push
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
     steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get Job ID
        id: get-job-id
        run: |
          TOKEN="$GIT_TOKEN"  # Replace with the name of your secret
          WORKFLOW_NAME="CI"  # Replace with the name of your workflow
          API_URL="https://api.github.com/repos/$GITHUB_REPOSITORY/actions/workflows/$WORKFLOW_NAME/runs?event=workflow_run"
          JOB_ID=$(curl -s -X GET -H "Authorization: token $TOKEN" $API_URL | jq -r '.workflow_runs[0].jobs[0].id')
          echo "::set-output name=job_id::$JOB_ID"

      - name: Display Job ID
        run: echo "Job ID --> ${{ steps.get-job-id.outputs.job_id }}"





