name: Pages and Deployment
on: push
jobs:
  checkoutCode:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci