name: Publish Sarif Template
on: 
  push:
    branch:
      - internal_portal_changes
jobs:
  uploadArtifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Upload summary html
        uses: actions/upload-artifact@v3
        with:
          name: Sarif-Report
          path: summary.html
          retention-days: 5
      - name: Download summary html
        uses: actions/download-artifact@v2
        with:
           name: Sarif-Report
  deploy:
    needs: uploadArtifact
    permissions:
      pages: write      
      id-token: write 
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: summary.html
    #   - name: Deploy in pages
    #     id: deployment
    #     uses: actions/deploy-pages@v2
