name: Publish Sarif Template
on: 
  push:
    branch:
      - internal_portal_changes
jobs:
  uploadArtifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Upload index html
        uses: actions/upload-artifact@v3
        with:
          name: Report
          path: test.html
          retention-days: 5
     
  deploy:
    runs-on: ubuntu-latest
    needs: uploadArtifact
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps: 
      - name: Download index html
        uses: actions/download-artifact@v2
        with:
           name: Report
           path: ./report
      # - name: Configure pages
      #   uses: actions/configure-pages@v1
      # - name: upload pages artifact
      #   uses: actions/upload-pages-artifact@v2
      #   with:
      #     name: Report
      #     path: ./report
      - name: Deploy code
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./report
      # - name: Deploy code
      #   id: deployment
      #   uses: actions/deploy-pages@v1
      #   with:
      #     artifact_name: Report
      #     token: ${{secrets.github_token}}
      # - name: Deploy code
      #   id: deployment
      #   uses: crazy-max/ghaction-github-pages@v4
      #   with:
      #     artifact_name: Report
      #     publish_dir: ./report
      #     build_dir: ./report
      #     domain: github.com
      #     target_branch: gh-pages
      #   env:
      #     GITHUB_PAGES: true
      #     GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
    

  
    