name: Publish Sarif Template
on: 
  push:
    branch:
      - internal_portal_changes
jobs:
  uploadArtifact:
    runs-on: ubuntu-latest
    steps:
      - name: Upload summary html
        uses: actions/upload-artifact@v3
        with:
          name: Sarif-Report
          path: dist
          retention-days: 5
      # - name: Download summary html
      #   uses: actions/download-artifact@v2
      #   with:
      #      name: Sarif-Report
      # - name: Deploy in pages
      #   uses: actions/deploy-pages@v2
      #   with:
      #     artifact_name: summary.html