name: Publish GitHub Pages
on: workflow_dispatch
jobs:
  publishPages:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build App
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pages
          path: |
            dist
            package.json
          if-no-files-found: error
      